### ISSUE TITLE
Lottie animation won't display

### ISSUE THREAD

**Issue by FernandoCCNunes** [PatilShreyas/MaterialDialog-Android#30]
After following implementation of the dialog, the animation won't be displayed like in the examples provided.

Here is what i did:
`// Material Design`
`implementation 'com.google.android.material:material:1.2.0-alpha06'`
`// Material Dialog Library`
`implementation 'com.shreyaspatil:MaterialDialog:2.1'`
`// Lottie Animation Library`
`implementation 'com.airbnb.android:lottie:3.4.0'`

Added the animation used in your examples to the raw folder

![image](https://user-images.githubusercontent.com/26973653/82920024-4f0db380-9f66-11ea-9fba-9211e36e668b.png)

Called dialog
`val mDialog = MaterialDialog.Builder(activity)`
`     .setTitle("Remove?")`
`     .setMessage("Are you sure want to remove this book?")`
` .setCancelable(false)`
`      .setPositiveButton("Remove", R.drawable.ic_delete_white_24dp) { _, _ ->`
` remove(book, initialBooks.indexOf(book))`
`  }`
`.setNegativeButton("Cancel", R.drawable.ic_close_24dp) { dialog, _ ->`
`     dialog.dismiss()`
`}`
`.setAnimation(R.raw.deletion_one_file)`
`  .build()`

`        mDialog.show()`

This is the result
![image](https://user-images.githubusercontent.com/26973653/82920689-1fab7680-9f67-11ea-8af9-f87546bd0a7c.png)

This is inside of a `Activity()`

I even tried measuring the `mDialog.animationView` and returns `height: 350` but `width: -1`

update 1: 
I get this error when `build()` function is called
`W/System.err: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x2
W/System.err:     at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1152)
        at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:1028)
        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1107)
        at android.content.res.Resources.getColorStateList(Resources.java:1126)
        at android.content.Context.getColorStateList(Context.java:709)
        at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:492)
        at com.shreyaspatil.MaterialDialog.AbstractDialog.createView(AbstractDialog.java:180)
        at com.shreyaspatil.MaterialDialog.MaterialDialog.<init>(MaterialDialog.java:36)
        at com.shreyaspatil.MaterialDialog.MaterialDialog$Builder.build(MaterialDialog.java:166)
        at com.guia.app.activities.MainActivity.setViews(MainActivity.kt:56)
        at com.guia.app.activities.MainActivity.onCreate(MainActivity.kt:35)
        at android.app.Activity.performCreate(Activity.java:7989)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3316)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3485)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7478)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)`

**Comment by PatilShreyas** [comment]
@FernandoCCNunes Is it landscape orientation of device while testing this?

**Comment by FernandoCCNunes** [comment]
yes it is, it actually works in portrait, is there any fix/workaround for this?

**Comment by PatilShreyas** [comment]
Actually it's available in the older version of this dialog but that
animations doesn't look good in landscape orientation. So it's not
available in landscape mode.

**Comment by FernandoCCNunes** [comment]
Is there a way I can extend the MaterialDialog class and change it's behavior or would I have to fork this repository, because as I said, its an app meant for Tablets, while in Android mobile devices I understand there is no space to display the dialog and the animation at the same time and the only option is to remove animation from displaying in landscape, you could have some calculation of the screen height to determine if there is space or not to display the animation, and even a function in the `.Builder` like `setDisplayInLandscape()`, just an idea, either way, love this library, good work

**Comment by PatilShreyas** [comment]
Thanks. But what happens in Lottie is there are variety of animations and
each one is having different scale so it becomes weird to think about each
scale. That's why it's removed.

**Comment by FernandoCCNunes** [comment]
I understand, I will fork it and handle that myself, thank you for your time

**Comment by Damercy** [comment]
The device is in portrait mode yet animation is not displayed. Same error log as above:

```kotlin
W/System.err: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x2
        at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1100)
        at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:976)
W/System.err:     at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1055)
        at android.content.res.Resources.getColorStateList(Resources.java:1032)
        at android.content.Context.getColorStateList(Context.java:651)
        at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:494)
        at dev.shreyaspatil.MaterialDialog.AbstractDialog.createView(AbstractDialog.java:181)
        at dev.shreyaspatil.MaterialDialog.MaterialDialog.<init>(MaterialDialog.java:36)
        at dev.shreyaspatil.MaterialDialog.MaterialDialog$Builder.build(MaterialDialog.java:178)
        at ai.microfinance.speech2txtpoc.screens.LocationDetailActivity.showRequiredDocsPrompt(LocationDetailActivity.kt:89)
        at ai.microfinance.speech2txtpoc.screens.LocationDetailActivity.access$showRequiredDocsPrompt(LocationDetailActivity.kt:26)
        at ai.microfinance.speech2txtpoc.screens.LocationDetailActivity$getDocsPrompt$docsDialog$2.onClick(LocationDetailActivity.kt:68)
        at dev.shreyaspatil.MaterialDialog.AbstractDialog$2.onClick(AbstractDialog.java:128)
        at android.view.View.performClick(View.java:6608)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:782)
        at android.view.View$PerformClick.run(View.java:25905)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6869)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
```

I'm calling BottomSheet as follows:
```kotlin
   val docsDialog =  getSheet(
            getString(R.string.ready_docs),
            getString(R.string.are_docs_ready),
            false
        )
            .setPositiveButton(
                getString(R.string.yes),
                R.drawable.choice_check_ic
            ) { dialog, _ ->
                  // actions
            }
            .setNegativeButton(
                getString(R.string.no),
                R.drawable.cross_image_square_failure
            ) { dialog, _ ->
                // actions
            }
            .build()

        docsDialog.apply {
            // Setting a background image in lottieAnimView instead of an animation
            animationView.setImageDrawable(ContextCompat.getDrawable(this,R.drawable.id_collections))
            show()
        }
```

getSheet() is a helper method that just returns a BottomSheetMaterialDialog.Builder

Any help is appreciated! 😅
